# Generated by Django 5.0.4 on 2024-04-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('apellido', models.TextField(max_length=100)),
                ('matricula', models.IntegerField()),
                ('campus', models.TextField(max_length=20)),
                ('carrera', models.TextField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('materias', models.IntegerField()),
            ],
        ),
    ]
